apiVersion: v1
kind: Service
metadata:
  name: payment-prod-svc # Service Name
  namespace: "{{ .Release.Namespace }}" # Service Namespace
spec:
  selector:
    app: payment-prod # Map the Service with the specified selected Pods
  type: ClusterIP # Internal Service to be used by other PODs / Services only.
  ports:
    - name: payment-prod-port # Name of the PORT
      port: 10023 # Service Port Number
      targetPort: payment-prod-cp # Redirect to Application PORT
      protocol: TCP # TCP Protocol