apiVersion: v1
kind: Service
metadata:
  name: payment-svc # Service Name
  namespace: "{{ .Release.Namespace }}" # Service Namespace
spec:
  selector:
    app: payment # Map the Service with the specified selected Pods
  type: ClusterIP # Internal Service to be used by other PODs / Services only.
  ports:
    - name: payment-port # Name of the PORT
      port: 10000 # Service Port Number
      targetPort: payment-cp # Redirect to Application PORT
      protocol: TCP # TCP Protocol