auth: 
  image: "nginx:latest"
  minReplica: 1
  maxReplica: 10
  requests: 
    cpu:
    memory:
    
crons: 
  image: "609459977430.dkr.ecr.ap-south-2.amazonaws.com/sx-api-crons:DR0.1"
  minReplica: 1
  maxReplica: 10
  requests: 
    cpu:
    memory:
    

dt: 
  image: "609459977430.dkr.ecr.ap-south-2.amazonaws.com/sx-api-dt:DR0.2"
  minReplica: 1
  maxReplica: 10
  requests: 
    cpu:
    memory:
    
enach: 
  image: "609459977430.dkr.ecr.ap-south-2.amazonaws.com/sx-api-enach:DR0.1"
  minReplica: 1
  maxReplica: 10
  requests: 
    cpu:
    memory:
    
masters: 
  image: "609459977430.dkr.ecr.ap-south-2.amazonaws.com/sx-api-masters:DR0.1"
  minReplica: 1
  maxReplica: 10
  requests: 
    cpu:
    memory:
    
openMandate: 
  image: "nginx:latest"
  minReplica: 1
  maxReplica: 10
  requests: 
    cpu:
    memory:
    
payment: 
  image: "609459977430.dkr.ecr.ap-south-2.amazonaws.com/sx-api-payment:DR0.4"
  minReplica: 1
  maxReplica: 10
  saRoleARN: "arn:aws:iam::609459977430:role/hyd-dr-eks-payment-sa-role"
  requests: 
    cpu:
    memory:

    
reports: 
  image: "609459977430.dkr.ecr.ap-south-2.amazonaws.com/sx-api-reports:DR0.1"
  minReplica: 1
  maxReplica: 10
  requests: 
    cpu:
    memory:
    
scanBase: 
  image: "609459977430.dkr.ecr.ap-south-2.amazonaws.com/sx-api-scanbase:DR0.3"
  minReplica: 1
  maxReplica: 10
  requests: 
    cpu:
    memory:
    
sftp: 
  image: "609459977430.dkr.ecr.ap-south-2.amazonaws.com/sx-api-sftp:DR0.1"
  minReplica: 1
  maxReplica: 10
  requests: 
    cpu:
    memory:
    
utilities: 
  image: "609459977430.dkr.ecr.ap-south-2.amazonaws.com/sx-api-utilities:DR0.3"
  minReplica: 1
  maxReplica: 10
  requests: 
    cpu:
    memory:


