apiVersion: v1
kind: Service
metadata:
  name: crons-svc # Service Name
  namespace: "{{ .Release.Namespace }}" # Service Namespace
spec:
  selector:
    app: crons-prod # Map the Service with the specified selected Pods
  type: ClusterIP # Internal Service to be used by other PODs / Services only.
  ports:
    - name: crons-port # Name of the PORT
      port: 10000 # Service Port Number
      targetPort: crons-cp # Redirect to Application PORT
      protocol: TCP # TCP Protocol