apiVersion: v1
kind: Service
metadata:
  name: masters-svc # Service Name
  namespace: "{{ .Release.Namespace }}" # Service Namespace
spec:
  selector:
    app: masters-prod # Map the Service with the specified selected Pods
  type: ClusterIP # Internal Service to be used by other PODs / Services only.
  ports:
    - name: masters-port # Name of the PORT
      port: 10000 # Service Port Number
      targetPort: masters-cp # Redirect to Application PORT
      protocol: TCP # TCP Protocol
