apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility-prod-depl
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: utility-prod-depl
spec:
  selector:
    matchLabels:
      app: utility-prod
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: utility-prod
    spec:
      serviceAccountName: payment-sa
      affinity:  # Add the affinity section here
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                - eks-nodes-dr-hyd-private-nodes
      containers:
        - name: utility-prod
          image: "{{.Values.utilities.image}}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2500m
              memory: 5Gi
          env:
            - name: TZ
              value: Asia/Kolkata
          volumeMounts:
            - name: tzdata
              mountPath: /usr/share/zoneinfo
          ports:
            - containerPort: 10022
              name: utility-prod-cp
      volumes:
        - name: tzdata
          hostPath:
            path: /usr/share/zoneinfo
      restartPolicy: Always
