apiVersion: v1
kind: Service
metadata:
  name: utility-prod-svc # Service Name
   # Service Namespace
spec:
  selector:
    app: utility-prod # Map the Service with the specified selected Pods
  type: ClusterIP # Internal Service to be used by other PODs / Services only.
  ports:
    - name: utility-prod-port # Name of the PORT
      port: 10022 # Service Port Number
      targetPort: utility-prod-cp # Redirect to Application PORT
      protocol: TCP # TCP Protocol
