apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-prod-depl
  
  labels:
    app: reports-prod-depl
spec:
  selector:
    matchLabels:
      app: reports-prod
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: reports-prod
    spec:
      serviceAccountName: reports-prod-sa
      affinity:  # Add the affinity section here
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                - SystemX-Prod-Node-Group
      containers:
        - name: reports-prod
          image: "{{.Values.reports.image}}"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 10018
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 7
          resources:
            requests:
              cpu: 1200m
              memory: 3Gi
            limits:
              cpu: 1500m
              memory: 6Gi
          env:
            - name: TZ
              value: Asia/Kolkata
          volumeMounts:
            - name: tzdata
              mountPath: /usr/share/zoneinfo
          ports:
            - containerPort: 10018
              name: reports-prod-cp
      volumes:
        - name: tzdata
          hostPath:
            path: /usr/share/zoneinfo
      restartPolicy: Always
