apiVersion: v1
kind: Service
metadata:
  name: reports-prod-svc # Service Name
   # Service Namespace
spec:
  selector:
    app: reports-prod # Map the Service with the specified selected Pods
  type: ClusterIP # Internal Service to be used by other PODs / Services only.
  ports:
    - name: reports-prod-port # Name of the PORT
      port: 10018 # Service Port Number
      targetPort: reports-prod-cp # Redirect to Application PORT
      protocol: TCP # TCP Protocol
