apiVersion: v1
kind: Service
metadata:
  name: om-prod-svc # Service Name
  namespace: "{{ .Release.Namespace }}" # Service Namespace
spec:
  selector:
    app: om-prod # Map the Service with the specified selected Pods
  type: ClusterIP # Internal Service to be used by other PODs / Services only.
  ports:
    - name: om-prod-port # Name of the PORT
      port: 10013 # Service Port Number
      targetPort: om-prod-cp # Redirect to Application PORT
      protocol: TCP # TCP Protocol