apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-prod-depl
  namespace: "{{ .Release.Namespace }}"
labels:
    app: auth-prod-depl
spec:
  selector:
    matchLabels:
      app: auth-prod
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth-prod
    spec:
      serviceAccountName: auth-prod-sa
      affinity:  # Add the affinity section here
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                - eks-nodes-dr-hyd-private-nodes
      containers:
        - name: auth-prod
          image: "{{.Values.auth.image}}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 400m
              memory: 1Gi
          env:
            - name: TZ
              value: Asia/Kolkata
          volumeMounts:
            - name: tzdata
              mountPath: /usr/share/zoneinfo
          ports:
            - containerPort: 10010
              name: auth-prod-cp
      volumes:
        - name: tzdata
          hostPath:
            path: /usr/share/zoneinfo
      restartPolicy: Always