apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-prod-hpa # HPA Name
  namespace: "{{ .Release.Namespace }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-prod-depl # Deployment Name to Scale the Selected Deployment
  minReplicas: {{.Values.auth.minReplica}} # Min. Number of Replicas
  maxReplicas: {{.Values.auth.maxReplica}} # Max. Number of Replicas
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60 # Number of seconds after which Scale In occurs
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
     # selectPolicy: Max
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
            #selectPolicy: Max
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60