apiVersion: v1
kind: Service
metadata:
  name: auth-prod-svc # Service Name
   # Service Namespace
spec:
  selector:
    app: auth-prod # Map the Service with the specified selected Pods
  type: ClusterIP # Internal Service to be used by other PODs / Services only.
  ports:
    - name: auth-prod-port # Name of the PORT
      port: 10010 # Service Port Number
      targetPort: auth-prod-cp # Redirect to Application PORT
      protocol: TCP # TCP Protocol