apiVersion: v1
kind: Service
metadata:
  name: scanb-prod-svc # Service Name
  namespace: "{{ .Release.Namespace }}" # Service Namespace
spec:
  selector:
    app: scanb-prod # Map the Service with the specified selected Pods
  type: ClusterIP # Internal Service to be used by other PODs / Services only.
  ports:
    - name: scanb-prod-port # Name of the PORT
      port: 10012 # Service Port Number
      targetPort: scanb-prod-cp # Redirect to Application PORT
      protocol: TCP # TCP Protocol
